### YamlMime:Landing

title: Configuration Manager troubleshooting
summary: Welcome to Configuration Manager troubleshooting. These articles explain how to determine, diagnose, and fix issues that you might encounter when you use Microsoft Endpoint Configuration Manager. In the navigation pane on the left, browse through the article list or use the search box to find issues and solutions.
metadata:
  title: Configuration Manager troubleshooting
  description: Landing page for Configuration Manager troubleshooting articles.
  ms.service: configuration-manager
  ms.topic: landing-page
  author: helenclu
  ms.author: luche
  ms.date: 02/11/2025

# linkListType: architecture | concept | deploy | download | get-started | how-to-guide | learn | overview | quickstart | reference | tutorial | video | whats-new

landingContent:

 # Card
  - title: Content management
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Troubleshoot content distribution
            url: content-management/troubleshoot-content-distribution.md
