### YamlMime:Landing

title: VM deployment issues
summary: Welcome to VM deployment issues. These articles explain how to determine, diagnose, and fix issues that you might encounter when you deploy an Azure Virtual Machine. In the navigation pane on the left, browse through the article list or use the search box to find issues and solutions.

metadata:
  title: VM deployment issues
  description: Documentation for troubleshooting common issues with deploying an Azure Virtual Machine.
  services: virtual-machines
  ms.service: virtual-machines #Required; service per approved list. service slug assigned to your service by ACOM.
  ms.subservice: vm-deploy
  ms.topic: landing-page # Required
  author: genlin  #Required; your GitHub user alias, with correct capitalization.
  ms.author: Travis.Maier #Required; microsoft alias of author; optional team alias.
  ms.date: 05/18/2021

# linkListType: architecture | concept | deploy | download | get-started | how-to-guide | learn | overview | quickstart | reference | tutorial | video | whats-new

landingContent:
# Cards and links should be based on top customer tasks or top subjects
# Start card title with a verb
  # Card (optional)
  - title: New Deployment Planning
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Overview of the Azure Compute Unit - Azure Virtual Machines
            url: /azure/virtual-machines/acu
          - text: VM sizes - Azure Virtual Machines
            url: /azure/virtual-machines/sizes
          - text: Azure subscription limits and quotas - Azure Resource Manager
            url: /azure/azure-resource-manager/management/azure-subscription-service-limits
          - text: Availability options for Azure Virtual Machines - Azure Virtual Machines
            url: /azure/virtual-machines/availability
          - text: Azure Products by Region
            url: https://azure.microsoft.com/global-infrastructure/services
          - text: Templates overview - Azure Resource Manager
            url: /azure/azure-resource-manager/templates/overview
          - text: Pricing Overview-How Azure Pricing Works
            url: https://azure.microsoft.com/pricing

          
  # Card (optional)
  - title: Image Deployment & Management
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Cloud-init-enabled VM takes a long time to start up
            url: cloud-init-deployment-delay.md
          - text: Prepare a Windows VHD to upload to Azure
            url: /azure/virtual-machines/windows/prepare-for-upload-vhd-image
          - text: Create VM from a managed image in Azure
            url: /azure/virtual-machines/windows/create-vm-generalized-managed
          - text: Share VM images with Shared Galleries
            url: /azure/virtual-machines/shared-image-galleries

  # Card (optional)
  - title: Troubleshoot Deployment Failures
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Troubleshooting Azure VM allocation failures - Virtual Machines
            url: allocation-failure.md
          - text: Troubleshoot common deployment errors - Azure Resource Manager
            url: /azure/azure-resource-manager/templates/common-deployment-errors
          - text: Quota errors - Azure Resource Manager
            url: /azure/azure-resource-manager/templates/error-resource-quota
          - text: SKU not available errors - Azure Resource Manager
            url: /azure/azure-resource-manager/templates/error-sku-not-available
          - text: Troubleshoot deploying Windows virtual machine issues in Azure - Virtual Machines
            url: troubleshoot-deploy-vm-windows.md
          - text: Troubleshoot deploying Linux virtual machine issues in Azure - Virtual Machines
            url: troubleshoot-deploy-vm-linux.md
          - text: Invalid template errors - Azure Resource Manager
            url: /azure/azure-resource-manager/templates/error-invalid-template
          - text: RequestDisallowedByPolicy error - Azure Resource Manager
            url: /azure/azure-resource-manager/templates/error-policy-requestdisallowedbypolicy