### YamlMime:Landing

title: Azure Automation troubleshooting documentation
summary: Welcome to Azure Automation troubleshooting. These articles explain how to determine, diagnose, and fix various issues that you might encounter when you use Azure Automation. In the navigation pane on the left, browse through the article list or use the search box to find issues and solutions.

metadata:
  title: Troubleshoot common issues with Azure Automation
  description: Documentation for troubleshooting common issues with Azure Automation. # Required; article description that is displayed in search results. < 160 chars.
  services: azure
  ms.service: azure-automation
  ms.topic: landing-page # Required
  author: genlin  #Required; your GitHub user alias, with correct capitalization.
  ms.author: genli #Required; microsoft alias of author; optional team alias.
  ms.date: 04/30/2025

# linkListType: architecture | concept | deploy | download | get-started | how-to-guide | learn | overview | quickstart | reference | tutorial | video | whats-new

landingContent:

# Card
  - title: Azure Automation
    linkLists:
      - linkListType: how-to-guide
        links:                                                               
          - text: Automation modifications aren't reflected in the portal
            url: configuration/modifications-not-reflect-portal.md
          - text: Find-AzureRmResource returns error
            url: updates/find-azurermresource-fails.md
          - text: How to capture Azure Automation-scripted diagnostics
            url: runbooks/automation-scripted-diagnostic-capture.md
          - text: How to capture debug stream
            url: runbooks/capture-debug-stream-automation-runbook.md
          - text: Reinstall Operations Management Suite Agent
            url: runbooks/reinstall-oms-agent-linux.md
