### YamlMime:Landing

title: Azure DevOps troubleshooting documentation
summary: Welcome to Azure DevOps troubleshooting. These articles explain how to determine, diagnose, and fix issues that you might encounter when you use Azure DevOps. In the navigation pane on the left, browse through the article list or use the search box to find issues and solutions.

metadata:
  title: Troubleshoot Azure DevOps issues
  description: Documentation for troubleshooting common issues with Azure DevOps. # Required; article description that is displayed in search results. < 160 chars.
  services: DevOps
  ms.service: azure-devops #Required; service per approved list. service slug assigned to your service by ACOM.
  ms.topic: landing-page # Required
  author: genlin  #Required; your GitHub user alias, with correct capitalization.
  ms.author: genli #Required; microsoft alias of author; optional team alias.
  ms.date: 04/30/2025
  
# linkListType: architecture | concept | deploy | download | get-started | how-to-guide | learn | overview | quickstart | reference | tutorial | video | whats-new

landingContent:

 # Card
  - title: Client Connectivity
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Office Integration add-in does not run
            url: ./office-add-in-not-run.md
          - text: Rename the Azure DevOps Service URL
            url: ./rename-service-url.md
          - text: Server specified can't be reached error
            url: ./server-specified-could-not-be-reached-error-occurs.md
  - title: Documentation and Support
    linkLists:      
      - linkListType: reference
        links:          
          - text: Azure DevOps documentation 
            url: /azure/devops
          - text: Azure DevOps Services support
            url: https://azure.microsoft.com/en-us/support/devops
          - text: Developer Community 
            url: https://developercommunity.visualstudio.com/home
